### ISSUE TITLE
Update docker-compose version (automatically)

### ISSUE THREAD

**Issue by LeSpocky** [netz39/ansible-role-host-docker#4]
Currently in *defaults/main.yml* there is `docker_compose_version: "1.27.4"` and that has to be updated once new releases are published.  A bot should do that.

**Comment by LeSpocky** [comment]
While reading through Dependabot tickets I think, that one does *not* support it:

1. https://github.com/dependabot/dependabot-core/issues/390
2. https://github.com/dependabot/dependabot-core/issues/7189

We need something else here, at least if we don't wanna wait forever for that feature appearing in Dependabot.

**Comment by LeSpocky** [comment]
The [prominent role we borrow from here](https://github.com/geerlingguy/ansible-role-docker) does not bump `docker_compose_version` automatically 🤷🏼‍♂️ .

**Comment by penguineer** [comment]
Question is: Do we need the external `docker-compose`? Apparently this function has been moved into the docker CLI client and is just provided as an alias now: https://docs.docker.com/compose/migrate/

**Comment by 24367dfa** [comment]
Then lets remove the external component from the role.

**Comment by LeSpocky** [comment]
As far as I understood, docker compose v2 is a plugin now, which has to be installed separately.  In the back of my head I remember someone questioned if both are compatible?  But if we are currently not using it, we should just start over with v2 once a need rises again.
